# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pass_the_booking', '0003_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(max_length=254)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pass_the_booking.Client')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pass_the_booking.Property')),
            ],
        ),
    ]
